### ISSUE TITLE
add animations/visuals for the different sorting algorithms

### ISSUE THREAD

**Issue by heratyian** [DPI-WE/patterns-of-enterprise-application-architecture-intro#2]

**Comment by thierrychau** [comment]
Some good one here for bubble sort and selection sort: https://s-satsangi.medium.com/insertion-sort-selection-sort-and-bubble-sort-5eb16d55a4de

**Comment by thierrychau** [comment]
Is this issue in the correct repo? https://github.com/DPI-WE/ruby-data-structures-algorithms-intro?tab=readme-ov-file

**Comment by heratyian** [comment]
> Is this issue in the correct repo? https://github.com/DPI-WE/ruby-data-structures-algorithms-intro?tab=readme-ov-file

Good catch 🙈

**Comment by heratyian** [comment]
https://github.com/DPI-WE/ruby-data-structures-algorithms-intro/issues/6
